CREATE TABLE dataset.template (
    key1 string,
    key2 string,
    key3 string,
    key4 string,
    STATUS string,
    date1 TIMESTAMP OPTIONS(description="yyyy-MM-dd HH:mm:ssz"),
    qty1 NUMERIC OPTIONS(description="14,4"),
    key5 string,
    key6 string,
    qty2 NUMERIC OPTIONS(description="14,4"),
    date2 TIMESTAMP OPTIONS(description="yyyy-MM-dd HH:mm:ssz"),
    key7 string,
    key8 string,
    timestamp1 TIMESTAMP OPTIONS(description="yyyy-MM-dd HH:mm:ssz"),
    timestamp2 TIMESTAMP OPTIONS(description="yyyy-MM-dd HH:mm:ssz"),
    id1 string,
    id2 string,
    id3 string,
    id4 string,
    id5 NUMERIC OPTIONS(description="5,0"),
    rank TIMESTAMP OPTIONS(description="-8|yyyy-MM-dd HH:mm:ss"))